import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration 007 — shop catalog split + listing pricing.
 *
 * - Replaces `gamification.shop_items` with `items`, `shop_listings`, `earned_items`.
 * - Preserves legacy `shop_items.id` as `items.id` for existing `transactions.item_id`.
 * - Listing pricing: `base_price`, per-rank prices, per-badge promotions, per-student limit.
 * - Group-scoped shop categories: `item_categories` + `items.category_id` FK.
 * - Item catalog image: `items.image_ref` (drive UUID, same as `groups.image_ref`).
 */
const UP_SQL = `
CREATE TABLE IF NOT EXISTS gamification.item_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id integer NOT NULL REFERENCES education.groups(id) ON DELETE CASCADE,
  name character varying(100) NOT NULL,
  description text,
  display_order integer,
  CONSTRAINT item_categories_group_name_unique UNIQUE (group_id, name)
);

CREATE INDEX IF NOT EXISTS item_categories_group_id_idx ON gamification.item_categories (group_id);

CREATE TABLE IF NOT EXISTS gamification.items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id integer NOT NULL REFERENCES education.groups(id),
  category_id integer,
  image_ref character varying(255),
  name character varying(100) NOT NULL,
  educational_description text
);

CREATE INDEX IF NOT EXISTS items_group_id_idx ON gamification.items (group_id);
CREATE INDEX IF NOT EXISTS items_category_id_idx ON gamification.items (category_id);

ALTER TABLE gamification.items
  ADD COLUMN IF NOT EXISTS category_id integer;

ALTER TABLE gamification.items
  ADD COLUMN IF NOT EXISTS image_ref character varying(255);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'items_category_id_fkey'
      AND conrelid = 'gamification.items'::regclass
  ) THEN
    ALTER TABLE gamification.items
      ADD CONSTRAINT items_category_id_fkey
      FOREIGN KEY (category_id) REFERENCES gamification.item_categories(id)
      ON DELETE SET NULL;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS gamification.shop_listings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id integer NOT NULL UNIQUE REFERENCES gamification.items(id) ON DELETE CASCADE,
  base_price integer NOT NULL,
  stock_quantity integer,
  per_student_limit integer
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'gamification'
      AND table_name = 'shop_listings'
      AND column_name = 'price'
  ) AND NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'gamification'
      AND table_name = 'shop_listings'
      AND column_name = 'base_price'
  ) THEN
    ALTER TABLE gamification.shop_listings RENAME COLUMN price TO base_price;
  END IF;
END $$;

ALTER TABLE gamification.shop_listings
  ADD COLUMN IF NOT EXISTS per_student_limit integer;

CREATE TABLE IF NOT EXISTS gamification.shop_listing_rank_prices (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_listing_id integer NOT NULL REFERENCES gamification.shop_listings(id) ON DELETE CASCADE,
  rank_id integer NOT NULL REFERENCES gamification.ranks(id) ON DELETE CASCADE,
  price integer NOT NULL,
  CONSTRAINT shop_listing_rank_prices_listing_rank_unique UNIQUE (shop_listing_id, rank_id)
);

CREATE INDEX IF NOT EXISTS shop_listing_rank_prices_listing_id_idx
  ON gamification.shop_listing_rank_prices (shop_listing_id);

CREATE INDEX IF NOT EXISTS shop_listing_rank_prices_rank_id_idx
  ON gamification.shop_listing_rank_prices (rank_id);

CREATE TABLE IF NOT EXISTS gamification.shop_listing_badge_promotions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shop_listing_id integer NOT NULL REFERENCES gamification.shop_listings(id) ON DELETE CASCADE,
  badge_id integer NOT NULL REFERENCES gamification.badges(id) ON DELETE CASCADE,
  promotion_type character varying(20) NOT NULL,
  value integer NOT NULL,
  CONSTRAINT shop_listing_badge_promotions_listing_badge_unique UNIQUE (shop_listing_id, badge_id),
  CONSTRAINT shop_listing_badge_promotions_type_check
    CHECK (promotion_type IN ('percent', 'fixed'))
);

CREATE INDEX IF NOT EXISTS shop_listing_badge_promotions_listing_id_idx
  ON gamification.shop_listing_badge_promotions (shop_listing_id);

CREATE INDEX IF NOT EXISTS shop_listing_badge_promotions_badge_id_idx
  ON gamification.shop_listing_badge_promotions (badge_id);

CREATE TABLE IF NOT EXISTS gamification.earned_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id integer NOT NULL REFERENCES gamification.enrollments(id) ON DELETE CASCADE,
  item_id integer NOT NULL REFERENCES gamification.items(id) ON DELETE RESTRICT,
  quantity integer NOT NULL DEFAULT 1,
  CONSTRAINT earned_items_enrollment_item_unique UNIQUE (enrollment_id, item_id)
);

CREATE INDEX IF NOT EXISTS earned_items_enrollment_id_idx ON gamification.earned_items (enrollment_id);
CREATE INDEX IF NOT EXISTS earned_items_item_id_idx ON gamification.earned_items (item_id);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'gamification'
      AND table_name = 'shop_items'
  ) THEN
    INSERT INTO gamification.items (id, group_id, name)
    SELECT
      si.id,
      si.group_id,
      'Item ' || si.id::text
    FROM gamification.shop_items si
    WHERE si.group_id IS NOT NULL
    ON CONFLICT (id) DO NOTHING;

    INSERT INTO gamification.shop_listings (item_id, base_price, stock_quantity)
    SELECT si.id, si.price, si.quantity
    FROM gamification.shop_items si
    WHERE EXISTS (SELECT 1 FROM gamification.items i WHERE i.id = si.id)
    ON CONFLICT (item_id) DO NOTHING;

    PERFORM setval(
      pg_get_serial_sequence('gamification.items', 'id'),
      COALESCE((SELECT MAX(id) FROM gamification.items), 1)
    );

    ALTER TABLE gamification.transactions
      DROP CONSTRAINT IF EXISTS transakcje_id_przedmiotu_fkey;

    DROP TABLE gamification.shop_items;

    DROP SEQUENCE IF EXISTS gamification.przedmioty_w_sklepie_id_seq;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'transactions_item_id_fkey'
      AND conrelid = 'gamification.transactions'::regclass
  ) THEN
    ALTER TABLE gamification.transactions
      ADD CONSTRAINT transactions_item_id_fkey
      FOREIGN KEY (item_id) REFERENCES gamification.items(id);
  END IF;
END $$;
`.trim();

const DOWN_SQL = `
ALTER TABLE gamification.transactions
  DROP CONSTRAINT IF EXISTS transactions_item_id_fkey;

CREATE TABLE IF NOT EXISTS gamification.shop_items (
  id integer NOT NULL,
  group_id integer,
  price integer NOT NULL,
  quantity integer
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'gamification'
      AND c.relname = 'przedmioty_w_sklepie_id_seq'
  ) THEN
    CREATE SEQUENCE gamification.przedmioty_w_sklepie_id_seq
      AS integer
      START WITH 1
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      CACHE 1;
  END IF;
END $$;

ALTER SEQUENCE gamification.przedmioty_w_sklepie_id_seq OWNED BY gamification.shop_items.id;

ALTER TABLE gamification.shop_items
  ALTER COLUMN id SET DEFAULT nextval('gamification.przedmioty_w_sklepie_id_seq'::regclass);

INSERT INTO gamification.shop_items (id, group_id, price, quantity)
SELECT
  i.id,
  i.group_id,
  sl.base_price,
  sl.stock_quantity
FROM gamification.items i
INNER JOIN gamification.shop_listings sl ON sl.item_id = i.id;

SELECT setval(
  'gamification.przedmioty_w_sklepie_id_seq',
  COALESCE((SELECT MAX(id) FROM gamification.shop_items), 1)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'przedmioty_w_sklepie_pkey'
      AND conrelid = 'gamification.shop_items'::regclass
  ) THEN
    ALTER TABLE gamification.shop_items
      ADD CONSTRAINT przedmioty_w_sklepie_pkey PRIMARY KEY (id);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'przedmioty_w_sklepie_id_grupy_fkey'
      AND conrelid = 'gamification.shop_items'::regclass
  ) THEN
    ALTER TABLE gamification.shop_items
      ADD CONSTRAINT przedmioty_w_sklepie_id_grupy_fkey
      FOREIGN KEY (group_id) REFERENCES education.groups(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'transakcje_id_przedmiotu_fkey'
      AND conrelid = 'gamification.transactions'::regclass
  ) THEN
    ALTER TABLE gamification.transactions
      ADD CONSTRAINT transakcje_id_przedmiotu_fkey
      FOREIGN KEY (item_id) REFERENCES gamification.shop_items(id);
  END IF;
END $$;

DROP INDEX IF EXISTS shop_listing_badge_promotions_badge_id_idx;
DROP INDEX IF EXISTS shop_listing_badge_promotions_listing_id_idx;
DROP TABLE IF EXISTS gamification.shop_listing_badge_promotions;

DROP INDEX IF EXISTS shop_listing_rank_prices_rank_id_idx;
DROP INDEX IF EXISTS shop_listing_rank_prices_listing_id_idx;
DROP TABLE IF EXISTS gamification.shop_listing_rank_prices;

DROP INDEX IF EXISTS earned_items_item_id_idx;
DROP INDEX IF EXISTS earned_items_enrollment_id_idx;
DROP TABLE IF EXISTS gamification.earned_items;
DROP TABLE IF EXISTS gamification.shop_listings;

ALTER TABLE gamification.items
  DROP CONSTRAINT IF EXISTS items_category_id_fkey;

DROP INDEX IF EXISTS items_category_id_idx;
DROP INDEX IF EXISTS items_group_id_idx;
DROP TABLE IF EXISTS gamification.items;

DROP INDEX IF EXISTS item_categories_group_id_idx;
DROP TABLE IF EXISTS gamification.item_categories;
`.trim();

export class ShopItemsCatalogSplit0000000000007 implements MigrationInterface {
  name = 'ShopItemsCatalogSplit0000000000007';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(UP_SQL);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(DOWN_SQL);
  }
}
