import type { MigrationInterface, QueryRunner } from 'typeorm';

const UP_SQL = `
CREATE TABLE IF NOT EXISTS gamification.default_item_templates (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(100) NOT NULL,
  story_description text,
  educational_description text,
  base_price integer NOT NULL
);

ALTER TABLE gamification.items
  ADD COLUMN IF NOT EXISTS story_description text;

INSERT INTO gamification.default_item_templates (name, story_description, educational_description, base_price) VALUES
('+0,5 OCENY', 'Najwyższa Rada Królików przyznaje specjalną nagrodę za szczególne zasługi.', 'Podniesienie oceny POZYTYWNEJ o pół stopnia.', 30),
('+3% DO OCENY', 'Wielka Marchewka dodaje królikowi punktów mocy.', '+3 punkty procentowe do ogólnego wyniku studenta/studentki.', 25),
('POPRAWA_1 BEZP', 'Statek trafia do hangaru ochronnego.', 'Możliwość ponownego napisania (poprawy) wejściówki z zamrożeniem obecnego wyniku (czyli nie można pogorszyć wyniku).', 20),
('POPRAWA_1', 'Awaryjny powrót statku do bazy.', 'Możliwość ponownego napisania (poprawy) wejściówki.', 15),
('ZAL WEJ', 'Statek wrócił z misji uszkodzony, ale wrócił.', 'Zaliczenie słabo napisanej wejściówki na 50%.', 15),
('+10% WEJ', 'Wsparcie dowództwa królików.', '+10 punktów procentowych do wejściówki (maksymalnie 100% w wyniku).', 10),
('+5% WEJ', 'Flota dosyła dodatkowe zapasy.', '+5 punktów procentowych do wejściówki (maksymalnie 100% w wyniku).', 5),
('+5 MINUT WEJ', 'Spowolnienie czasu w nadprzestrzeni.', 'Dodatkowe 5 minut na wejściówce.', 5),
('KONSULTACJA', 'Konsultacja z Mistrzem Królików.', 'Możliwość zadania pytania (nie wprost o prawidłową odpowiedź) prowadzącemu podczas wejściówki.', 5)
ON CONFLICT DO NOTHING;
`;

const DOWN_SQL = `
DROP TABLE IF EXISTS gamification.default_item_templates;

ALTER TABLE gamification.items
  DROP COLUMN IF EXISTS story_description;
`;

export class AddStoryDescriptionAndTemplates0000000000009 implements MigrationInterface {
  name = 'AddStoryDescriptionAndTemplates0000000000009';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(UP_SQL);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(DOWN_SQL);
  }
}
