import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration 003 — enrollment codes table, legacy backfill, drop groups.entry_code.
 */
const UP_SQL = `
CREATE TABLE IF NOT EXISTS education.enrollment_codes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id integer NOT NULL REFERENCES education.groups(id) ON DELETE CASCADE,
  code character varying(10) NOT NULL,
  expires_at timestamp without time zone,
  max_uses integer,
  use_count integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT NOW(),
  updated_at timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT enrollment_codes_group_code_unique UNIQUE (group_id, code)
);

CREATE INDEX IF NOT EXISTS enrollment_codes_group_id_idx ON education.enrollment_codes (group_id);
CREATE INDEX IF NOT EXISTS enrollment_codes_code_idx ON education.enrollment_codes (code);

INSERT INTO education.enrollment_codes (group_id, code, is_active)
SELECT g.id, g.entry_code, true
FROM education.groups g
WHERE g.entry_code IS NOT NULL
  AND TRIM(g.entry_code) <> ''
ON CONFLICT (group_id, code) DO NOTHING;

ALTER TABLE education.groups DROP COLUMN IF EXISTS entry_code;
`.trim();

const DOWN_SQL = `
ALTER TABLE education.groups ADD COLUMN IF NOT EXISTS entry_code character varying(10);

UPDATE education.groups g
SET entry_code = ec.code
FROM (
  SELECT DISTINCT ON (group_id) group_id, code
  FROM education.enrollment_codes
  ORDER BY group_id, id DESC
) ec
WHERE g.id = ec.group_id;

DROP INDEX IF EXISTS education.enrollment_codes_code_idx;
DROP INDEX IF EXISTS education.enrollment_codes_group_id_idx;
DROP TABLE IF EXISTS education.enrollment_codes;
`.trim();

export class EnrollmentCodesTable0000000000003 implements MigrationInterface {
  name = 'EnrollmentCodesTable0000000000003';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(UP_SQL);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(DOWN_SQL);
  }
}
