import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Migration 004 — IdP certificates table and organization SAML columns (schema only; no org seed).
 */
const UP_SQL = `
CREATE TABLE IF NOT EXISTS auth.idp_certificates (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id integer NOT NULL REFERENCES auth.organizations(id) ON DELETE CASCADE,
  certificate text NOT NULL,
  fingerprint text NOT NULL,
  valid_from timestamptz,
  valid_until timestamptz,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idp_certificates_organization_id_idx ON auth.idp_certificates (organization_id);

ALTER TABLE auth.organizations
  ADD COLUMN IF NOT EXISTS contact_email character varying(255),
  ADD COLUMN IF NOT EXISTS contact_phone character varying(64),
  ADD COLUMN IF NOT EXISTS entity_id text,
  ADD COLUMN IF NOT EXISTS metadata_url text,
  ADD COLUMN IF NOT EXISTS sso_login_url text,
  ADD COLUMN IF NOT EXISTS sso_logout_url text,
  ADD COLUMN IF NOT EXISTS certificate_id integer,
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT NOW();

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'organizations_certificate_id_fkey'
  ) THEN
    ALTER TABLE auth.organizations
      ADD CONSTRAINT organizations_certificate_id_fkey
      FOREIGN KEY (certificate_id) REFERENCES auth.idp_certificates(id);
  END IF;
END $$;
`.trim();

const DOWN_SQL = `
ALTER TABLE auth.organizations DROP CONSTRAINT IF EXISTS organizations_certificate_id_fkey;

ALTER TABLE auth.organizations
  DROP COLUMN IF EXISTS updated_at,
  DROP COLUMN IF EXISTS created_at,
  DROP COLUMN IF EXISTS is_active,
  DROP COLUMN IF EXISTS certificate_id,
  DROP COLUMN IF EXISTS sso_logout_url,
  DROP COLUMN IF EXISTS sso_login_url,
  DROP COLUMN IF EXISTS metadata_url,
  DROP COLUMN IF EXISTS entity_id,
  DROP COLUMN IF EXISTS contact_phone,
  DROP COLUMN IF EXISTS contact_email;

DROP INDEX IF EXISTS auth.idp_certificates_organization_id_idx;
DROP TABLE IF EXISTS auth.idp_certificates;
`.trim();

export class IdpOrganizations0000000000004 implements MigrationInterface {
  name = 'IdpOrganizations0000000000004';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(UP_SQL);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(DOWN_SQL);
  }
}
